config/routes.rb
Challenge::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :disputes do
    resources :videos
  end

  post "disputes/vote"

  get "home/index"

  root :to => 'home#index'

end

app/models/dispute.rb
class Dispute < ActiveRecord::Base
  has_many :videos

  validates :description, :presence => true,  :length => { :minimum => 40 }
  validates :record,      :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_and_belongs_to_many :disputes

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else # Create a user with a stub password.
      User.create!(:email => data.email)
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
      end
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :dispute

  validates :number,        :presence => true
  validates :youtube_id,    :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/disputes_controller.rb
class DisputesController < ApplicationController
  before_filter :authenticate_user!, :only => [:vote, :new, :create]

  # GET /disputes
  # GET /disputes.json
  def index
    if params[:voting]
      @disputes = Dispute.where("votes is null or votes < 10")
    else
      @disputes = Dispute.where("votes >= 10")
    end
  end

  # GET /disputes/1
  # GET /disputes/1.json
  def show
    @dispute = Dispute.find(params[:id])
  end

  # GET /disputes/new
  # GET /disputes/new.json
  def new
    @dispute = Dispute.new
  end

  # GET /disputes/1/edit
  def edit
    @dispute = Dispute.find(params[:id])
  end

  # POST /disputes
  # POST /disputes.json
  def create
    @dispute  = Dispute.new(params[:dispute])

    if @dispute.save
      redirect_to @dispute, notice: 'Dispute was successfully created.'
    else # Dispute failed to save
      render action: "new"
    end
  end

  # PUT /disputes/1
  # PUT /disputes/1.json
  def update
    @dispute = Dispute.find(params[:id])

    if @dispute.update_attributes(params[:dispute])
      redirect_to @dispute, notice: 'Dispute was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /disputes/1
  # DELETE /disputes/1.json
  def destroy
    @dispute = Dispute.find(params[:id])
    @dispute.destroy

    redirect_to disputes_url
  end

  def vote
    @dispute = Dispute.find(params[:dispute_id])
    if current_user and !current_user.disputes.exists? @dispute
      @dispute.votes ? @dispute.votes += 1 : @dispute.votes = 1
      current_user.disputes << @dispute
      current_user.save
      @dispute.save
    end
    redirect_to :back
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if Dispute.count > 0
      # Get featured video
      @max_votes = Dispute.maximum('votes')
      @disputeFeatured = Dispute.find_all_by_votes(@max_votes).first
      @bestScore = @disputeFeatured.videos.maximum('number') if @disputeFeatured.record == 0
      @bestScore = @disputeFeatured.videos.minimum('number') if @disputeFeatured.record == 1
      @featured = @disputeFeatured.videos.find_all_by_number(@bestScore).first
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    @dispute = Dispute.find(params[:dispute_id])
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @dispute  = Dispute.find params[:dispute_id]
    @video    = Video.new

  end

  # GET /videos/1/edit
  def edit
    @dispute  = Dispute.find params[:dispute_id]
    @video    = Video.find params[:id]
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])
    @video.dispute_id = params[:dispute_id]
    if @video.save
      redirect_to dispute_video_path(@video.dispute, @video), notice: 'Video was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      redirect_to @video.dispute, notice: 'Video was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def record_to_string(record)
    if record == 0
      "More"
    elsif record == 1
      "Less"
    else
      "Crazy"
    end
  end

  def dispute_order(dispute)
    if dispute.record == 0
      'number DESC'
    else
      'number ASC'
    end

  end

end

app/helpers/disputes_helper.rb
module DisputesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/disputes/_form.html.haml
= semantic_form_for @dispute  do |f|
  = f.inputs do
    = f.input :description
    = f.input :record, :as => :radio, :collection => [['More', 0], ['Less', 1], ['Crazy', 2]]
  = f.buttons

app/views/disputes/edit.html.haml
%h1 Editing dispute

= render "form"

app/views/disputes/index.html.haml
.disputes
  %table{:id => 'top10ideas', :cellpadding => "0", :cellspacing => "0"}
    - @disputes.each do |dispute|
      %tr{:id => "ideahover"}
        %td{:id => "idea"}
          = link_to dispute.description, dispute_path(dispute)
        %td{:id => "info"}
          = link_to (image_tag "tu.png"), {:controller => 'disputes', :action => 'vote', :dispute_id => dispute.id}, :method => :post
          = dispute.votes

app/views/disputes/new.html.haml
%h1 New dispute

= render "form"

app/views/disputes/show.html.haml
%p
  %b Description:
  = @dispute.description

%p
  %b Record:
  = record_to_string @dispute.record

- if @dispute.votes and @dispute.votes >= 10
  %p
    = link_to 'Respond', new_dispute_video_path(@dispute)

- if @dispute.videos and !@dispute.videos.empty?
  - @dispute.videos.order(dispute_order(@dispute)).each do |video|
    = link_to dispute_video_path(video.dispute, video) do
      %table{:border => "0", :id => "moore"}
        %td{:id => "mooore"}
          %table{:id => "mv"}
            %td
              = image_tag "http://img.youtube.com/vi/#{video.youtube_id}/1.jpg"
            %td{:width => "8"}
            %td{:valign => "top"}
              %p
                %b
                  Record:
                  = video.number
              = truncate(video.description, :length => 350)
            %td{:width => "8"}

= link_to 'Edit', edit_dispute_path(@dispute)
= link_to 'Back', disputes_path

app/views/home/index.html.haml
#left
  #prin
    %table{:id => "vp", :border => "0", :align => "center"}
      %tr
        %td{:colspan => "5", :height => "10"}
      %tr
        %td{:width => "8"}
        %td{:width => "280"}
          - if @featured
            %iframe{ :width => "292", :height => "226", :src => "http://www.youtube.com/embed/#{@featured.youtube_id}" , :frameborder => "0", :allowfullscreen => "" }
        %td{:width => "20"}
        %td{:valign => "top"}
          - if @featured
            = truncate(@featured.dispute.description, :length => 400)
            %p
              %b Added:
              = @featured.created_at.strftime("%d/%m/%y")
            %p
              = link_to "Respond", new_dispute_video_path(@featured.dispute, @featured)

  #more
    - Video.limit(8).each do |video|
      = link_to dispute_video_path(video.dispute, video) do
        %table{:border => "0", :id => "moore"}
          %td{:id => "mooore"}
            %table{:id => "mv"}
              %td
                = image_tag "http://img.youtube.com/vi/#{video.youtube_id}/1.jpg"
              %td{:width => "8"}
              %td{:valign => "top"}
                = truncate(video.description, :length => 350)
              %td{:width => "8"}

#right
  #desafio
    = link_to "Add your Challenge", new_dispute_path
  #top10top
    #top10
      %table{:id => 'top10ideas', :cellpadding => "0", :cellspacing => "0"}
        - Dispute.limit(10).each do |dispute|
          %tr{:id => "ideahover"}
            %td{:id => "idea"}
              = link_to truncate(dispute.description, :length => 100), dispute_path(dispute)
            %td{:id => "info"}
              = link_to (image_tag "tu.png"), {:controller => 'disputes', :action => 'vote', :dispute_id => dispute.id}, :method => :post
              = dispute.votes

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Challenge
    = stylesheet_link_tag 'application'
    = javascript_include_tag  'application'
    = csrf_meta_tags
  %body
    #head
      %br
      = link_to (image_tag "fblogin.png", :align => "right", :style => 'position:relative;right:40px;'), user_omniauth_authorize_path(:facebook)
      %table{:id => "menu"}
        %tr
          %td{:width => "250"}
          %td{:id => "menuhover"}= link_to "What's on", disputes_path
          %td{:id => "menuhover"}= link_to "Vote", disputes_path(:voting => true)
          %td{:id => "menuhover"}= link_to "Arround me"
          %td{:id => "menuhover"}= link_to "Top"
          %td{:width => "10"}
    #main
      = yield

app/views/videos/_form.html.haml
= semantic_form_for [@dispute, @video] do |f|
  = f.inputs do
    = f.input :number
    = f.input :description
    = f.input :youtube_id
  = f.buttons

app/views/videos/edit.html.haml
%h1 Edit Video

= render 'form'

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th Number
    %th Description
    %th Dispute
    %th
    %th
    %th

- @videos.each do |video|
  %tr
    %td= video.number
    %td= video.description
    %td= video.dispute_id
    %td= link_to 'Show', dispute_video_path(video.dispute, video)
    %td= link_to 'Edit', edit_dispute_video_path(video.dispute, video)
    %td= link_to 'Destroy', dispute_video_path(video.dispute, video), confirm: 'Are you sure?', method: :delete
%br

= link_to 'Challenge accepted', new_dispute_video_path(@dispute)

app/views/videos/new.html.haml
%h1 New Video

= render "form"

app/views/videos/show.html.haml
%p
  %b Number:
  = @video.number

%p
  %b Description:
  = @video.description

%p
  %b= link_to "Dispute", dispute_path(@video.dispute)

.video
  %iframe{ :width => "560", :height => "315", :src => "http://www.youtube.com/embed/#{@video.youtube_id}" , :frameborder => "0", :allowfullscreen => "" }
  = link_to "Respond", new_dispute_video_path(@video.dispute)

= link_to 'Edit', edit_dispute_video_path(@video)
= link_to 'Back', dispute_videos_path